from typing import Protocol


class Transport(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def send(self, data: bytes) -> None: ...
    def read(self) -> bytes: ...
